# Generated by Django 3.1 on 2021-03-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default=1, max_length=300, verbose_name='amount/portion'),
            preserve_default=False,
        ),
    ]
